#! /usr/bin/env python3

# author:   Denisov Denis
# date:     01.06.2016
#
# Task (https://projecteuler.net/problem=2):
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed 4 000 000,
# find the sum of the even-valued terms.

max_value = 4000000

pair = [1, 2]

new = 0
result = 2

while new < max_value:

    result += new
    for i in (1, 2, 3):
        new = pair[0] + pair[1]
        pair[0], pair[1] = (pair[1], new)

print(result)




